
(() => {
'use strict';
const T=window.PRAG_TRIP, KEY='prag-reise-state-v1';
const defaults={tab:'today',currentDay:'sun',completed:{},skipped:{},decisions:{},ticket24At:null,ticketCountdown:null,parking:{choice:null,parked:false,name:null,lat:null,lon:null,parkedAt:null,spaceNote:'',floor:'',row:'',spot:'',photoData:null,pickupAt:'2026-09-03T10:30'},theme:'system',geoEnabled:false,notifications:false,lastLocation:null,notified:{},tripStartedAt:null,dayWake:{mon:'07:30',tue:'06:45',wed:'08:30',thu:'07:30'},dayLeave:{mon:'08:15',tue:'07:30',wed:'09:30',thu:'09:30'},klementinumTime:'',eurPerCzk:0.0414289,eurUpdated:'2026-08-29T23:19:00Z'};
let state=load(); let watchId=null; let timerId=null;
function load(){try{return deepMerge(structuredClone(defaults),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return structuredClone(defaults)}}
function deepMerge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k]&&typeof a[k]==='object')a[k]=deepMerge(a[k],b[k]);else a[k]=b[k]}return a}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const $=s=>document.querySelector(s), view=$('#view');
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function dayById(id){return T.days.find(d=>d.id===id)}
function todayByDate(){const iso=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());return T.days.find(d=>d.date===iso)}
function eligible(stop){if(!stop.condition)return true;return state.decisions[stop.condition.key]===stop.condition.value}
function stops(dayId){return dayById(dayId).stops.filter(eligible)}
function pendingStops(dayId){return stops(dayId).filter(s=>!state.completed[s.id]&&!state.skipped[s.id])}
function currentStop(dayId=state.currentDay){return pendingStops(dayId)[0]||null}
function nextStop(dayId=state.currentDay){return pendingStops(dayId)[1]||null}
function progress(dayId){const ss=stops(dayId),done=ss.filter(s=>state.completed[s.id]||state.skipped[s.id]).length;return {done,total:ss.length,pct:ss.length?Math.round(done/ss.length*100):0}}
function fmtDate(iso){return new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit',timeZone:'Europe/Prague'}).format(new Date(iso+'T12:00:00+02:00'))}
function nowPrague(){return new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Prague'}).format(new Date())}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2600)}
function transportIcon(t){return ({walk:'🚶',transit:'🚋',car:'🚗'})[t]||'➡️'}
function routeUrl(stop,mode){if(!stop)return '#';const dest=stop.lat&&stop.lon?`${stop.lat},${stop.lon}`:stop.query||stop.name;const travel=mode==='car'?'driving':mode==='transit'?'transit':'walking';return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(dest)}&travelmode=${travel}`}
function appleUrl(stop,mode){if(!stop)return '#';const dest=stop.lat&&stop.lon?`${stop.lat},${stop.lon}`:stop.query||stop.name;const f=mode==='car'?'d':mode==='transit'?'r':'w';return `https://maps.apple.com/?daddr=${encodeURIComponent(dest)}&dirflg=${f}`}
function searchFood(){window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('restaurants near me'),'_blank')}
function price(czk){return `${czk} CZK · ≈ ${(czk*state.eurPerCzk).toFixed(2).replace('.',',')} €`}
function ticketActive(){if(!state.ticket24At)return null;const start=new Date(state.ticket24At),end=new Date(start.getTime()+24*3600e3),ms=end-Date.now();return {start,end,ms,active:ms>0}}
function timeLeft(ms){if(ms<=0)return 'abgelaufen';const h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000);return `${h} h ${m} min`}
function ticketCard(stop){if(!stop.ticket)return '';const p=T.prices[stop.ticket];let active='';if(stop.ticket==='24h'){const a=ticketActive();if(a?.active) active=`<div class="card ok"><b>✅ Bereits aktiv</b><br>Noch ${timeLeft(a.ms)} gültig.</div>`}
return `${active}<div class="ticketAlert"><h3>🔔 TICKET AKTIVIEREN</h3><b>4 × ${esc(p.label)}</b><br>${price(p.group)} gesamt<br><small>In PID Lítačka aktivieren. Danach 60 Sekunden warten.</small><a class="btn secondary full center" href="${T.links.pid}" target="_blank" rel="noopener">PID Lítačka öffnen</a><button class="btn full" data-action="ticketactivate" data-ticket="${stop.ticket}">Tickets jetzt aktiviert</button></div>`}
function wikiImage(stop,imgElId){if(!stop?.wiki)return;const cacheKey='wikiimg:'+stop.wiki;const cached=localStorage.getItem(cacheKey);if(cached){setHeroImage(imgElId,cached,stop);return}fetch(`https://de.wikipedia.org/w/api.php?action=query&format=json&origin=*&prop=pageimages&pithumbsize=1200&titles=${encodeURIComponent(stop.wiki)}`).then(r=>r.json()).then(j=>{const pg=Object.values(j.query?.pages||{})[0];const src=pg?.thumbnail?.source;if(src){localStorage.setItem(cacheKey,src);setHeroImage(imgElId,src,stop)}}).catch(()=>{})}
function setHeroImage(id,src,stop){const wrap=document.getElementById(id);if(!wrap)return;wrap.innerHTML=`<img class="heroimg" src="${esc(src)}" alt="${esc(stop.name)}" loading="eager" referrerpolicy="no-referrer">`;}
function imgHtml(stop){return `<div id="heroImage" class="imgwrap"><div class="imgfallback">${esc(stop.icon||'📍')}</div></div>`}
function ticketStatusBanner(){const a=ticketActive();if(!a)return '';if(a.active)return `<div class="card ok"><div class="split"><div><b>🎟️ 24h-Ticket aktiv</b><div class="muted">noch ${timeLeft(a.ms)}</div></div><span class="bigvalue">✅</span></div></div>`;return `<div class="card warn"><b>🔔 24h-Ticket abgelaufen</b><div class="muted">Vor der nächsten ÖPNV-Fahrt neu prüfen.</div></div>`}
function currentDayAuto(){const td=todayByDate();if(td && !Object.values(state.completed).some(Boolean) && state.currentDay==='sun') state.currentDay=td.id}
function renderToday(){currentDayAuto();const day=dayById(state.currentDay),cur=currentStop(),next=nextStop(),pr=progress(day.id);let dist='';if(state.lastLocation&&cur?.lat){const m=Math.round(haversine(state.lastLocation.lat,state.lastLocation.lon,cur.lat,cur.lon));dist=`<div class="distanceBanner">📍 ${m<1000?m+' m':(m/1000).toFixed(1)+' km'} bis ${esc(cur.name)}</div>`}
if(!cur){view.innerHTML=`<div class="card center"><div class="bigvalue">✅</div><h1>${esc(day.label)} geschafft</h1><p>${esc(day.title)}</p>${nextDayHtml(day.id)}</div>`;return}
let special=specialAction(cur);const wake=state.dayWake[day.id],leave=state.dayLeave[day.id];view.innerHTML=`${dist}<div class="split"><div><div class="eyebrow">${esc(day.label)} · ${fmtDate(day.date)}</div><h1 class="heroTitle">${esc(day.title)}</h1></div><div class="chip">${pr.done}/${pr.total}</div></div><div class="progress"><span style="width:${pr.pct}%"></span></div>${ticketStatusBanner()}<section class="card"><div class="eyebrow">AKTUELLER HALT</div><div class="stopname">${esc(cur.icon)} ${esc(cur.name)}</div>${imgHtml(cur)}<div class="chips"><span class="chip">${transportIcon(cur.transport)} ${esc(cur.duration||'')}</span>${cur.kind==='attraction'?'<span class="chip warn">🎟️ Attraktion</span>':''}${cur.kind==='ticket'?'<span class="chip warn">🔔 Ticket</span>':''}</div><div class="meta"><b>Jetzt</b><span>${esc(cur.action||'')}</span><b>Hinweis</b><span>${esc(cur.note||'')}</span></div>${cur.ticket?ticketCard(cur):''}${special}<details><summary>📖 Warum sind wir hier?</summary><p class="guide">${esc(cur.guide||'Dieser Halt ist Teil eures geplanten Tagesablaufs.')}</p></details></section>${next?`<section class="card flat"><div class="eyebrow">NÄCHSTER HALT</div><div class="nextname">${esc(next.icon)} ${esc(next.name)}</div><div class="chips"><span class="chip">${transportIcon(next.transport)} ${esc(next.duration||'')}</span></div><div class="btnrow"><a class="btn primary center" href="${routeUrl(next,next.transport)}" target="_blank" rel="noopener">🗺 Google Maps</a><a class="btn secondary center" href="${appleUrl(next,next.transport)}" target="_blank" rel="noopener"> Karten</a></div>${next.transport==='transit'?`<a class="btn secondary full center" href="${T.links.pid}" target="_blank" rel="noopener">🚋 PID Lítačka / Live prüfen</a>`:''}</section>`:''}<button class="btn ok full" data-action="complete" data-id="${cur.id}">✅ ${cur.kind==='transit'?'Angekommen – weiter':'Erledigt / weiter'}</button><div class="btnrow"><button class="btn secondary" data-action="back">← Vorheriger Halt</button><button class="btn secondary" data-action="choose">Anderen Halt</button></div>${wake?`<div class="card info"><b>⏰ Tagesrhythmus</b><div class="muted">Aufstehen ${wake} · geplant los ${leave||'flexibel'}</div></div>`:''}`;wikiImage(cur,'heroImage')}
function specialAction(cur){
 if(cur.decision==='startdrive') return `<button class="btn primary full" data-action="startdrive">🚗 Jetzt losgefahren</button>`;
 if(cur.decision==='parking') return `<div class="separator"></div><h3>Wie viele Plätze sind bei Zličín 2 frei?</h3><div class="field"><input class="input" id="z2free" inputmode="numeric" placeholder="z. B. 18 freie Plätze"></div><a class="btn secondary full center" href="${T.parking.z2.url}" target="_blank">🌐 Offizielle Live-Belegung öffnen</a><div class="btnrow"><button class="btn ok" data-action="parkz2">✅ Hier parken</button><button class="btn warn" data-action="gotoz1">Zu voll → Zličín 1</button></div><button class="btn secondary full" data-action="otherparking">Anderer Parkplatz</button>`;
 if(cur.decision==='parkz1') return `<a class="btn secondary full center" href="${T.parking.z1.url}" target="_blank">🌐 Live-Belegung Zličín 1</a><button class="btn ok full" data-action="parkz1">✅ Hier geparkt</button>`;
 if(cur.decision==='kampa') return `<div class="btnrow"><button class="btn ok" data-decision="kampa" data-value="yes">✅ Kampa machen</button><button class="btn secondary" data-decision="kampa" data-value="no">❌ Überspringen</button></div>`;
 if(cur.decision==='monreturn') return `<div class="btnrow"><button class="btn secondary" data-decision="monreturn" data-value="walk">🚶 Zu Fuß</button><button class="btn primary" data-decision="monreturn" data-value="transit">🚋 ÖPNV</button></div>`;
 if(cur.decision==='lucerna') return `<div class="btnrow"><button class="btn ok" data-decision="lucerna" data-value="yes">✅ Machen</button><button class="btn secondary" data-decision="lucerna" data-value="no">❌ Überspringen</button></div>`;
 if(cur.decision==='kafka') return `<div class="btnrow"><button class="btn ok" data-decision="kafka" data-value="yes">✅ Machen</button><button class="btn secondary" data-decision="kafka" data-value="no">❌ Überspringen</button></div>`;
 if(cur.decision==='idiom') return `<div class="btnrow"><button class="btn ok" data-decision="idiom" data-value="yes">✅ 0–20 Min.</button><button class="btn warn" data-action="idiomMaybe">🤔 20–30 Min.</button></div><div class="btnrow"><button class="btn secondary" data-decision="idiom" data-value="no">❌ Über 30 Min.</button><button class="btn secondary" data-action="idiomLater">🔁 Später prüfen</button></div>`;
 if(cur.decision==='vysehrad') return `<div class="btnrow"><button class="btn ok" data-decision="vysehrad" data-value="yes">✅ Ja, Vyšehrad</button><button class="btn secondary" data-decision="vysehrad" data-value="no">❌ Nein, Hotel</button></div>`;
 if(cur.decision==='checkout') return checklistHtml(['Hotelzimmer kontrolliert','Ladegeräte','Ausweise','Gepäck','Autoschlüssel','Hotel ausgecheckt'],'checkout');
 if(cur.decision==='returncar') return `<button class="btn primary full" data-action="carroute">🅿️ Zum gespeicherten Auto navigieren</button>${checklistHtml(['Auto gefunden','Parkplatz bezahlt/ausgecheckt','Gepäck vollständig'],'returncar')}`;
 if(cur.kind==='food') return `<button class="btn primary full" data-action="food">🍴 Essen in der Nähe</button>`;
 return ''
}
function checklistHtml(items,key){return `<div class="list">${items.map((x,i)=>`<label class="listitem"><input type="checkbox" data-check="${key}-${i}"> <span>${esc(x)}</span></label>`).join('')}</div>`}
function nextDayHtml(id){const idx=T.days.findIndex(d=>d.id===id),n=T.days[idx+1];if(!n)return '<p>🇨🇿 Prag-Reise abgeschlossen.</p>';const wake=state.dayWake[n.id]||n.wake,leave=state.dayLeave[n.id]||n.leave;return `<div class="card info"><b>Morgen: ${esc(n.label)} – ${esc(n.title)}</b><p class="muted">Vorschlag: ${wake?wake+' aufstehen · ':''}${leave?leave+' los':''}</p><button class="btn primary full" data-action="switchday" data-day="${n.id}">Morgen öffnen</button></div>`}
function renderDays(){view.innerHTML=`<h1 class="heroTitle">📅 Reisetage</h1><p class="muted">Tippe einen Tag an, um ihn als aktuellen Tag zu öffnen.</p><div class="daygrid">${T.days.map(d=>{const p=progress(d.id);return `<button class="daycard ${state.currentDay===d.id?'current':''}" data-action="switchday" data-day="${d.id}"><div class="eyebrow">${esc(d.label)} · ${fmtDate(d.date)}</div><h3>${esc(d.title)}</h3><div class="muted">${esc(d.theme)}</div><div class="progress"><span style="width:${p.pct}%"></span></div><div class="split"><small>${p.done}/${p.total} erledigt</small><b>${p.pct}%</b></div></button>`}).join('')}</div><h2 class="sectionTitle">Aktueller Tag – Stationen</h2>${stopList(state.currentDay)}`}
function stopList(dayId){const ss=stops(dayId),cur=currentStop(dayId);return `<div class="list">${ss.map(s=>{const done=state.completed[s.id],skip=state.skipped[s.id],iscur=cur?.id===s.id;return `<button class="listitem ${done||skip?'done':''} ${iscur?'current':''}" data-action="jump" data-id="${s.id}" data-day="${dayId}"><span class="status">${done?'✅':skip?'⏭️':iscur?'➡️':'⬜'}</span><span class="body"><strong>${esc(s.icon)} ${esc(s.name)}</strong><small class="muted">${esc(s.duration||'')}</small></span></button>`}).join('')}</div>`}
function ticketRecommendation(){const d=state.currentDay,a=ticketActive();if(d==='sun')return '<b>Empfehlung Sonntag:</b> 4 × 24h (560 CZK), sobald ihr am P+R wirklich losfahrt. Das deckt Sonntag und – je nach Aktivierungszeit – Montagmorgen ab.';if(d==='mon')return a?.active?'<b>Empfehlung Montag:</b> Das Sonntag-24h-Ticket läuft noch – nichts neu aktivieren.':'<b>Empfehlung Montag:</b> Für den Weg mit Umstieg nach Strahov ist 90 Min. die stressfreie Wahl; abends bei kurzem Rückweg ggf. 30 Min.';if(d==='tue')return '<b>Empfehlung Dienstag:</b> Kein ÖPNV-Ticket geplant – fast alles zu Fuß.';if(d==='wed')return '<b>Empfehlung Mittwoch:</b> 30-Minuten-Gruppenaktivierungen für die kurzen Fahrten; bei Vyšehrad gilt das Ticket beim Umstieg weiter, solange die Zeit reicht.';return '<b>Empfehlung Donnerstag:</b> 4 × 90 Min. (184 CZK) für Hotel/Můstek → Zličín mit Gepäck und Zeitpuffer.'}
function renderTickets(){const a=ticketActive();view.innerHTML=`<h1 class="heroTitle">🎟️ Tickets</h1><div class="card info">${ticketRecommendation()}</div>${a?`<div class="card ${a.active?'ok':'warn'}"><div class="eyebrow">24-STUNDEN-TICKET</div><div class="bigvalue">${a.active?'✅ aktiv':'🔔 abgelaufen'}</div><p>${a.active?'Noch '+timeLeft(a.ms):'Vor nächster Fahrt neu prüfen.'}</p><small>Aktiviert: ${a.start.toLocaleString('de-DE')}<br>Gültig bis: ${a.end.toLocaleString('de-DE')}</small></div>`:`<div class="card"><b>Noch kein 24h-Ticket gespeichert.</b></div>`}<h2 class="sectionTitle">Preisvergleich · 4 Erwachsene</h2><div class="daygrid">${Object.entries(T.prices).map(([k,p])=>`<div class="card flat"><div class="eyebrow">${esc(p.label)}</div><div class="price">${p.group} CZK</div><div class="eur">≈ ${(p.group*state.eurPerCzk).toFixed(2).replace('.',',')} € · 4 × ${p.pp} CZK</div>${k!=='72h'?`<button class="btn secondary small full" data-action="ticketactivate" data-ticket="${k}">Als jetzt aktiviert markieren</button>`:''}</div>`).join('')}</div><div class="card flat"><b>Geplanter Restbedarf</b><div class="meta"><b>Montag</b><span>Rückweg ggf. 1 × Gruppenaktivierung 30 Min.</span><b>Dienstag</b><span>kein ÖPNV geplant</span><b>Mittwoch</b><span>2 Gruppenaktivierungen 30 Min.; mit Vyšehrad insgesamt 3</span><b>Donnerstag</b><span>1 Gruppenaktivierung 90 Min.</span></div></div><div class="card info"><b>💳 N26 + Mastercard</b><p class="muted">N26 verwendet bei Kartenzahlungen in Fremdwährung den Mastercard-Wechselkurs und erhebt laut N26 keine eigene Gebühr für Auslands-Kartenzahlungen. Die €-Werte hier sind eine Live-/Fallback-Näherung, nicht die endgültige Kartenabrechnung.</p><div class="btnrow"><button class="btn primary" data-action="fxrefresh">↻ EUR aktualisieren</button><a class="btn secondary center" href="${T.links.mastercard}" target="_blank">Mastercard exakt</a></div><small class="muted">Rate: 1 CZK ≈ ${state.eurPerCzk.toFixed(5)} €</small></div><div class="card warn"><b>🔔 60-Sekunden-Regel</b><p>Mobile PID-Lítačka-Tickets erst benutzen, wenn die Schutzfrist abgelaufen ist. Die App hier erinnert – das echte Ticket immer in PID Lítačka prüfen.</p></div>`}
function renderParking(){const p=state.parking;let cost='—';if(p.parkedAt){const end=new Date(p.pickupAt||'2026-09-03T10:30'),hrs=Math.max(0,(end-new Date(p.parkedAt))/3600000);const czk=hrs<=24?50:50+Math.ceil(hrs-24)*10;cost=price(czk)}view.innerHTML=`<h1 class="heroTitle">🅿️ Auto</h1><div class="card ${p.parked?'ok':''}"><div class="eyebrow">Status</div><div class="bigvalue">${p.parked?'✅ Auto geparkt':'Noch nicht gespeichert'}</div><p>${esc(p.name||'Ziel zunächst P+R Zličín 2')}</p>${p.parkedAt?`<small>Geparkt: ${new Date(p.parkedAt).toLocaleString('de-DE')}</small>`:''}</div><div class="card"><h3>P+R Live prüfen</h3><p class="muted">Die offizielle Prager Seite zeigt aktuelle freie Plätze. Eine statische GitHub-PWA kann diese fremde Seite wegen Browser-Sicherheitsregeln nicht verlässlich automatisch im Hintergrund auslesen.</p><div class="btnrow"><a class="btn primary center" href="${T.parking.z2.url}" target="_blank">Zličín 2 live</a><a class="btn secondary center" href="${T.parking.z1.url}" target="_blank">Zličín 1 live</a></div></div><div class="card"><h3>Parkplatzdetails</h3><div class="field"><label>Etage / Bereich</label><input class="input" id="pfloor" value="${esc(p.floor)}"></div><div class="btnrow"><div class="field"><label>Reihe</label><input class="input" id="prow" value="${esc(p.row)}"></div><div class="field"><label>Platz</label><input class="input" id="pspot" value="${esc(p.spot)}"></div></div><div class="field"><label>Notiz</label><input class="input" id="pnote" value="${esc(p.spaceNote)}" placeholder="z. B. neben Ausgang"></div><div class="field"><label>Foto vom Stellplatz</label><input class="input" type="file" accept="image/*" capture="environment" id="pphoto"></div>${p.photoData?`<img class="heroimg" src="${p.photoData}" alt="Parkplatzfoto">`:''}<button class="btn primary full" data-action="saveparkingnote">Speichern</button></div><div class="card"><h3>Geschätzte Parkkosten</h3><div class="field"><label>Geplante Abholung</label><input class="input" type="datetime-local" id="pickupAt" value="${esc(p.pickupAt||'')}"></div><div class="bigvalue">${cost}</div><small class="muted">Regel: 50 CZK erste 24 h, danach 10 CZK je weitere angefangene Stunde.</small></div>${p.parked?`<div class="btnrow"><button class="btn primary" data-action="carroute">🗺 Zum Auto</button><button class="btn secondary" data-action="savecarpos">📍 Position aktualisieren</button></div>`:''}`}
function renderPlaces(){view.innerHTML=`<h1 class="heroTitle">📍 Alle Orte</h1><p class="muted">Hier kannst du jederzeit zu einem bestimmten Halt springen. Der Fortschritt davor wird nicht automatisch gelöscht.</p>${T.days.map(d=>`<h2 class="sectionTitle">${esc(d.label)} · ${esc(d.title)}</h2>${stopList(d.id)}`).join('')}`}
function renderSettings(){view.innerHTML=`<h1 class="heroTitle">⚙️ Mehr & Einstellungen</h1><div class="card"><h3>Darstellung</h3><div class="toggle">${['system','light','dark'].map(x=>`<button class="btn secondary ${state.theme===x?'selected':''}" data-theme="${x}">${x==='system'?'System':x==='light'?'Hell':'Dunkel'}</button>`).join('')}</div></div><div class="card"><h3>📍 Standort & Hinweise</h3><p class="muted">Bei geöffneter PWA kann die Entfernung zum nächsten Halt angezeigt und bei Nähe ein Hinweis ausgelöst werden. iOS erlaubt einer normalen Web-App kein zuverlässiges permanentes Geofencing im Hintergrund.</p><button class="btn primary full" data-action="geo">${state.geoEnabled?'✅ Standort aktiv':'Standort aktivieren'}</button><button class="btn secondary full" data-action="notify">${state.notifications?'✅ Hinweise erlaubt':'Benachrichtigungen erlauben'}</button></div><div class="card"><h3>⏰ Zeiten</h3>${T.days.filter(d=>d.id!=='sun').map(d=>`<div class="split"><b>${d.label}</b><div style="display:flex;gap:6px"><input class="input timeinput" type="time" data-time="wake" data-day="${d.id}" value="${esc(state.dayWake[d.id]||'')}"><input class="input timeinput" type="time" data-time="leave" data-day="${d.id}" value="${esc(state.dayLeave[d.id]||'')}"></div></div>`).join('<div class="separator"></div>')}<div class="field"><label>Klementinum-Führung (optional)</label><input class="input" type="time" id="klemTime" value="${esc(state.klementinumTime)}"></div><button class="btn primary full" data-action="savetimes">Zeiten speichern</button></div><div class="card"><h3>🔗 Wichtige Links</h3><a class="btn secondary full center" href="${T.links.pid}" target="_blank">PID Lítačka</a><a class="btn secondary full center" href="${T.links.mastercard}" target="_blank">Mastercard Währungsrechner</a><a class="btn secondary full center" href="${T.links.hotel}" target="_blank">Hotel-Website</a></div><div class="card warn"><h3>Zurücksetzen</h3><button class="btn secondary full" data-action="resetday">Aktuellen Tag zurücksetzen</button><button class="btn warn full" data-action="resetall">Gesamten Urlaub zurücksetzen</button></div><div class="card info"><b>📱 Als App installieren</b><p class="muted">In Safari: Teilen → Zum Home-Bildschirm. Danach startet die Seite im App-Look und die Grunddaten funktionieren offline.</p></div><small class="muted">Prag Reise v${T.version}<br>${esc(T.sourcesNote)}</small>`}
function render(){applyTheme();$('#topDate').textContent=nowPrague();document.querySelectorAll('.navitem').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));({today:renderToday,days:renderDays,tickets:renderTickets,parking:renderParking,places:renderPlaces,settings:renderSettings}[state.tab]||renderToday)(); bindDynamic(); checkSchedule()}
function applyTheme(){document.documentElement.dataset.theme=state.theme==='system'?'':state.theme}
function bindDynamic(){const photo=$('#pphoto');if(photo)photo.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.parking.photoData=r.result;save();toast('Foto gespeichert');render()};r.readAsDataURL(f)})}
function complete(id){state.completed[id]=true;save();render();window.scrollTo({top:0,behavior:'smooth'})}
function back(){const day=dayById(state.currentDay),els=stops(day.id),idx=els.findIndex(s=>!state.completed[s.id]&&!state.skipped[s.id]);if(idx<=0){toast('Kein vorheriger Halt');return}const prev=els[idx-1];delete state.completed[prev.id];delete state.skipped[prev.id];save();render()}
function jump(day,id){state.currentDay=day;const ss=stops(day),idx=ss.findIndex(s=>s.id===id);for(let i=0;i<idx;i++)state.completed[ss[i].id]=true;delete state.completed[id];delete state.skipped[id];state.tab='today';save();render()}
function decision(k,v,cur){state.decisions[k]=v;if(cur)state.completed[cur.id]=true;save();render()}
function markPark(which){const x=T.parking[which];state.parking={...state.parking,choice:which,parked:true,name:x.name,lat:x.lat,lon:x.lon,parkedAt:new Date().toISOString()};state.decisions.parkingChoice=which;if(which==='z2')state.completed.sun_zlicin2=true;else state.completed.sun_zlicin1=true;save();toast(`${x.name} gespeichert`);render()}
function otherParking(){const name=prompt('Name oder Beschreibung des anderen Parkplatzes:');if(!name)return;state.parking={...state.parking,choice:'other',parked:true,name,parkedAt:new Date().toISOString()};state.decisions.parkingChoice='other';state.completed.sun_zlicin2=true;save();render()}
function startTicket(type){if(type==='24h')state.ticket24At=new Date().toISOString();state.ticketCountdown={type,startedAt:Date.now()};save();showCountdown()}
function showCountdown(){let left=60;modal(`<div class="center"><div class="eyebrow">PID LÍTAČKA</div><h2>🔔 Tickets aktiviert</h2><p>Noch nicht einsteigen / Metrobereich betreten.</p><div id="countdown" class="countdown">60</div><p>Nach Ablauf bitte das echte Ticket kurz in PID Lítačka prüfen.</p><button class="btn secondary full" data-action="closemodal">Abbrechen</button></div>`);clearInterval(timerId);timerId=setInterval(()=>{left--;const el=$('#countdown');if(el)el.textContent=Math.max(0,left);if(left<=0){clearInterval(timerId);modal(`<div class="center"><div class="bigvalue">✅</div><h2>60 Sekunden vorbei</h2><p>Ticket sollte jetzt gültig sein. Bitte kurz in PID Lítačka prüfen.</p><button class="btn ok full" data-action="closemodal">Weiter</button></div>`);notify('Tickets sollten jetzt gültig sein','Bitte kurz in PID Lítačka prüfen.')}},1000)}
function modal(html){$('#modalCard').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function chooseModal(){const d=state.currentDay;modal(`<h2>Anderen Halt auswählen</h2>${stopList(d)}<button class="btn secondary full" data-action="closemodal">Schließen</button>`)}
function carRoute(){const p=state.parking;if(p.lat&&p.lon)window.open(`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lon}&travelmode=walking`,'_blank');else window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.name||'P+R Zličín')}`,'_blank')}
function saveParkingNote(){state.parking.floor=$('#pfloor')?.value||'';state.parking.row=$('#prow')?.value||'';state.parking.spot=$('#pspot')?.value||'';state.parking.spaceNote=$('#pnote')?.value||'';state.parking.pickupAt=$('#pickupAt')?.value||state.parking.pickupAt;save();toast('Parkplatzdetails gespeichert');render()}
function saveCarPos(){if(!navigator.geolocation)return toast('Geolocation nicht verfügbar');navigator.geolocation.getCurrentPosition(pos=>{state.parking.lat=pos.coords.latitude;state.parking.lon=pos.coords.longitude;save();toast('Autoposition aktualisiert')},()=>toast('Standort konnte nicht gelesen werden'),{enableHighAccuracy:true})}
function enableGeo(){if(!navigator.geolocation)return toast('Standort nicht unterstützt');state.geoEnabled=true;save();startGeo();toast('Standort aktiviert');render()}
function startGeo(){if(!state.geoEnabled||watchId!==null||!navigator.geolocation)return;watchId=navigator.geolocation.watchPosition(pos=>{state.lastLocation={lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy,at:Date.now()};save();proximityCheck();if(state.tab==='today')render()},()=>{}, {enableHighAccuracy:true,maximumAge:15000,timeout:20000})}
function proximityCheck(){const cur=currentStop();if(!cur?.lat||!state.lastLocation)return;const m=haversine(state.lastLocation.lat,state.lastLocation.lon,cur.lat,cur.lon);if(m<120&&!state.notified[cur.id]){state.notified[cur.id]=Date.now();save();notify(`Fast da: ${cur.name}`,`Noch ungefähr ${Math.round(m)} m. Öffne Prag Reise für den nächsten Schritt.`);if(navigator.vibrate)navigator.vibrate([100,50,100])}}
function haversine(a,b,c,d){const R=6371000,r=x=>x*Math.PI/180,dp=r(c-a),dl=r(d-b),x=Math.sin(dp/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
async function enableNotify(){if(!('Notification'in window))return toast('Benachrichtigungen nicht unterstützt');const p=await Notification.requestPermission();state.notifications=p==='granted';save();toast(state.notifications?'Benachrichtigungen erlaubt':'Nicht erlaubt');render()}
function notify(title,body){if(state.notifications&&'Notification'in window&&Notification.permission==='granted'){try{new Notification(title,{body,icon:'./icon-192.png'})}catch(e){}}}
function checkSchedule(){if(state.tab!=='today')return;const day=dayById(state.currentDay);if(day.id==='tue'&&state.klementinumTime){const [h,m]=state.klementinumTime.split(':').map(Number),target=new Date(`${day.date}T${state.klementinumTime}:00+02:00`),mins=(target-Date.now())/60000; if(mins>0&&mins<45&&!state.notified.klementinumSoon){state.notified.klementinumSoon=Date.now();save();toast(`Klementinum in ${Math.round(mins)} Min. – Route prüfen`);notify('Klementinum bald',`Führung in etwa ${Math.round(mins)} Minuten.`)}}}
async function refreshFx(){try{const r=await fetch('https://api.frankfurter.app/latest?from=CZK&to=EUR');const j=await r.json();if(j?.rates?.EUR){state.eurPerCzk=j.rates.EUR;state.eurUpdated=new Date().toISOString();save();toast('EUR-Näherung aktualisiert');render();return}}catch(e){}toast('Live-Kurs nicht erreichbar – Fallback bleibt')}
function resetDay(){if(!confirm('Aktuellen Tag wirklich zurücksetzen?'))return;for(const s of dayById(state.currentDay).stops){delete state.completed[s.id];delete state.skipped[s.id]}save();render()}
function resetAll(){if(!confirm('Wirklich den GESAMTEN Urlaub zurücksetzen?'))return;if(!confirm('Alle Fortschritte, Tickets und Parkplatzdaten löschen?'))return;localStorage.removeItem(KEY);state=structuredClone(defaults);render()}
function startDrive(){state.tripStartedAt=new Date().toISOString();state.completed.sun_drive=true;save();if(navigator.geolocation)navigator.geolocation.getCurrentPosition(pos=>{state.lastLocation={lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy,at:Date.now()};save()},()=>{});window.open(routeUrl(T.days[0].stops[1],'car'),'_blank');render()}
function saveTimes(){document.querySelectorAll('.timeinput').forEach(x=>state[x.dataset.time==='wake'?'dayWake':'dayLeave'][x.dataset.day]=x.value);state.klementinumTime=$('#klemTime')?.value||'';save();toast('Zeiten gespeichert');render()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-tab]');if(nav){state.tab=nav.dataset.tab;save();render();return}const theme=e.target.closest('[data-theme]');if(theme){state.theme=theme.dataset.theme;save();render();return}const dec=e.target.closest('[data-decision]');if(dec){decision(dec.dataset.decision,dec.dataset.value,currentStop());return}const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;
 if(a==='complete')complete(el.dataset.id); else if(a==='back')back(); else if(a==='choose')chooseModal(); else if(a==='closemodal')closeModal(); else if(a==='switchday'){state.currentDay=el.dataset.day;state.tab='today';save();closeModal();render()} else if(a==='jump'){closeModal();jump(el.dataset.day,el.dataset.id)} else if(a==='startdrive')startDrive(); else if(a==='parkz2')markPark('z2'); else if(a==='gotoz1'){state.decisions.parkingChoice='z1';state.completed.sun_zlicin2=true;save();render()} else if(a==='parkz1')markPark('z1'); else if(a==='otherparking')otherParking(); else if(a==='ticketactivate')startTicket(el.dataset.ticket); else if(a==='food')searchFood(); else if(a==='carroute')carRoute(); else if(a==='saveparkingnote')saveParkingNote(); else if(a==='savecarpos')saveCarPos(); else if(a==='geo')enableGeo(); else if(a==='notify')enableNotify(); else if(a==='fxrefresh')refreshFx(); else if(a==='resetday')resetDay(); else if(a==='resetall')resetAll(); else if(a==='savetimes')saveTimes(); else if(a==='idiomMaybe'){modal('<h2>🤔 20–30 Minuten</h2><p>Wenn euch Idiom sehr wichtig ist, macht es jetzt. Sonst überspringen und später erneut prüfen.</p><div class="btnrow"><button class="btn ok" data-decision="idiom" data-value="yes">Jetzt machen</button><button class="btn secondary" data-decision="idiom" data-value="no">Überspringen</button></div>')} else if(a==='idiomLater'){state.decisions.idiom='no';state.completed.tue_idiom_choice=true;save();toast('Erstmal übersprungen – über Orte jederzeit zurück');render()}}
);
$('#quickStatusBtn').addEventListener('click',()=>{state.tab='today';save();render()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
applyTheme();startGeo();refreshFx();render();setInterval(()=>{$('#topDate').textContent=nowPrague();if(state.tab==='today')checkSchedule()},60000);
})();
